version: '3.7'

x-template: &flyway-template
  image: flyway/flyway:7.15.0
  command: -url=jdbc:mysql://db -schemas=... -user=root -password=root migrate
  volumes:
    - ./flyway/sql:/flyway/sql
    - ./flyway/conf:/flyway/conf

services:
  db:
    container_name: mysql_host
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=test_database
      - MYSQL_ROOT_PASSWORD=root
      - TZ='Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql/db/data:/var/lib/mysql
      - ./mysql/db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306
  flyway-clean:
    <<: *flyway-template
    command: clean
  flyway-migrate:
    <<: *flyway-template
    command: migrate
  flyway-info:
    <<: *flyway-template
    command: info
